
const englishBibleBooks = {
    1: "Genesis",
    2: "Exodus",
    3: "Leviticus",
    4: "Numbers",
    5: "Deuteronomy",
    6: "Joshua",
    7: "Judges",
    8: "Ruth",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Kings",
    12: "2 Kings",
    13: "1 Chronicles",
    14: "2 Chronicles",
    15: "Ezra",
    16: "Nehemiah",
    17: "Esther",
    18: "Job",
    19: "Psalms",
    20: "Proverbs",
    21: "Ecclesiastes",
    22: "Song of Solomon",
    23: "Isaiah",
    24: "Jeremiah",
    25: "Lamentations",
    26: "Ezekiel",
    27: "Daniel",
    28: "Hosea",
    29: "Joel",
    30: "Amos",
    31: "Obadiah",
    32: "Jonah",
    33: "Micah",
    34: "Nahum",
    35: "Habakkuk",
    36: "Zephaniah",
    37: "Haggai",
    38: "Zechariah",
    39: "Malachi",
    40: "Matthew",
    41: "Mark",
    42: "Luke",
    43: "John",
    44: "Acts",
    45: "Romans",
    46: "1 Corinthians",
    47: "2 Corinthians",
    48: "Galatians",
    49: "Ephesians",
    50: "Philippians",
    51: "Colossians",
    52: "1 Thessalonians",
    53: "2 Thessalonians",
    54: "1 Timothy",
    55: "2 Timothy",
    56: "Titus",
    57: "Philemon",
    58: "Hebrews",
    59: "James",
    60: "1 Peter",
    61: "2 Peter",
    62: "1 John",
    63: "2 John",
    64: "3 John",
    65: "Jude",
    66: "Revelation"
}

const spanishBibleBooks = {
    1: "Génesis",
    2: "Éxodo",
    3: "Levítico",
    4: "Números",
    5: "Deuteronomio",
    6: "Josué",
    7: "Jueces",
    8: "Rut",
    9: "1 Samuel",
    10: "2 Samuel",
    11: "1 Reyes",
    12: "2 Reyes",
    13: "1 Crónicas",
    14: "2 Crónicas",
    15: "Esdras",
    16: "Nehemías",
    17: "Ester",
    18: "Job",
    19: "Salmos",
    20: "Proverbios",
    21: "Eclesiastés",
    22: "Cantares",
    23: "Isaías",
    24: "Jeremías",
    25: "Lamentaciones",
    26: "Ezequiel",
    27: "Daniel",
    28: "Oseas",
    29: "Joel",
    30: "Amós",
    31: "Abdías",
    32: "Jonás",
    33: "Miqueas",
    34: "Nahúm",
    35: "Habacuc",
    36: "Sofonías",
    37: "Hageo",
    38: "Zacarías",
    39: "Malaquías",
    40: "Mateo",
    41: "Marcos",
    42: "Lucas",
    43: "Juan",
    44: "Hechos",
    45: "Romanos",
    46: "1 Corintios",
    47: "2 Corintios",
    48: "Gálatas",
    49: "Efesios",
    50: "Filipenses",
    51: "Colosenses",
    52: "1 Tesalonicenses",
    53: "2 Tesalonicenses",
    54: "1 Timoteo",
    55: "2 Timoteo",
    56: "Tito",
    57: "Filemón",
    58: "Hebreos",
    59: "Santiago",
    60: "1 Pedro",
    61: "2 Pedro",
    62: "1 Juan",
    63: "2 Juan",
    64: "3 Juan",
    65: "Judas",
    66: "Apocalipsis"
}

export const bibleBooks: { [key: string]: { [key: number]: string } } = {
    // "KJV": englishBibleBooks,
    // "NKJV": englishBibleBooks,
    // "RV1960": spanishBibleBooks,
    // "ESV": englishBibleBooks,
    // "NIV": englishBibleBooks,
    // "LBLA": spanishBibleBooks,
    "English": englishBibleBooks,
    "Spanish": spanishBibleBooks
}

const englishBibleVersionsBooksNumberOfChapters = {
    Genesis: 50,
    Exodus: 40,
    Leviticus: 27,
    Numbers: 36,
    Deuteronomy: 34,
    Joshua: 24,
    Judges: 21,
    Ruth: 4,
    '1 Samuel': 31,
    '2 Samuel': 24,
    '1 Kings': 22,
    '2 Kings': 25,
    '1 Chronicles': 29,
    '2 Chronicles': 36,
    Ezra: 10,
    Nehemiah: 13,
    Esther: 10,
    Job: 42,
    Psalms: 150,
    Proverbs: 31,
    Ecclesiastes: 12,
    'Song of Solomon': 8,
    Isaiah: 66,
    Jeremiah: 52,
    Lamentations: 5,
    Ezekiel: 48,
    Daniel: 12,
    Hosea: 14,
    Joel: 3,
    Amos: 9,
    Obadiah: 1,
    Jonah: 4,
    Micah: 7,
    Nahum: 3,
    Habakkuk: 3,
    Zephaniah: 3,
    Haggai: 2,
    Zechariah: 14,
    Malachi: 4,
    Matthew: 28,
    Mark: 16,
    Luke: 24,
    John: 21,
    Acts: 28,
    Romans: 16,
    '1 Corinthians': 16,
    '2 Corinthians': 13,
    Galatians: 6,
    Ephesians: 6,
    Philippians: 4,
    Colossians: 4,
    '1 Thessalonians': 5,
    '2 Thessalonians': 3,
    '1 Timothy': 6,
    '2 Timothy': 4,
    Titus: 3,
    Philemon: 1,
    Hebrews: 13,
    James: 5,
    '1 Peter': 5,
    '2 Peter': 3,
    '1 John': 5,
    '2 John': 1,
    '3 John': 1,
    Jude: 1,
    Revelation: 22
}

const spanishBibleVersionsBooksNumberOfChapters = {
    "Génesis": 50,
    "Éxodo": 40,
    "Levítico": 27,
    "Números": 36,
    "Deuteronomio": 34,
    "Josué": 24,
    "Jueces": 21,
    "Rut": 4,
    "1 Samuel": 31,
    "2 Samuel": 24,
    "1 Reyes": 22,
    "2 Reyes": 25,
    "1 Crónicas": 29,
    "2 Crónicas": 36,
    "Esdras": 10,
    "Nehemías": 13,
    "Ester": 10,
    "Job": 42,
    "Salmos": 150,
    "Proverbios": 31,
    "Eclesiastés": 12,
    "Cantares": 8,
    "Isaías": 66,
    "Jeremías": 52,
    "Lamentaciones": 5,
    "Ezequiel": 48,
    "Daniel": 12,
    "Oseas": 14,
    "Joel": 3,
    "Amós": 9,
    "Abdías": 1,
    "Jonás": 4,
    "Miqueas": 7,
    "Nahúm": 3,
    "Habacuc": 3,
    "Sofonías": 3,
    "Ageo": 2,
    "Zacarías": 14,
    "Malaquías": 4,
    "Mateo": 28,
    "Marcos": 16,
    "Lucas": 24,
    "Juan": 21,
    "Hechos": 28,
    "Romanos": 16,
    "1 Corintios": 16,
    "2 Corintios": 13,
    "Gálatas": 6,
    "Efesios": 6,
    "Filipenses": 4,
    "Colosenses": 4,
    "1 Tesalonicenses": 5,
    "2 Tesalonicenses": 3,
    "1 Timoteo": 6,
    "2 Timoteo": 4,
    "Tito": 3,
    "Filemón": 1,
    "Hebreos": 13,
    "Santiago": 5,
    "1 Pedro": 5,
    "2 Pedro": 3,
    "1 Juan": 5,
    "2 Juan": 1,
    "3 Juan": 1,
    "Judas": 1,
    "Apocalipsis": 22
}

export const bibleBooksNumberOfChapters: { [key: string]: { [key: string]: number } } = {
    // 'KJV': englishBibleVersionsBooksNumberOfChapters,
    // "NKJV": englishBibleVersionsBooksNumberOfChapters,
    // RV1960: spanishBibleVersionsBooksNumberOfChapters,
    // ESV: englishBibleVersionsBooksNumberOfChapters,
    // NIV: englishBibleVersionsBooksNumberOfChapters
    // LBLA: spanishBibleVersionsBooksNumberOfChapters,
    "English": englishBibleVersionsBooksNumberOfChapters,
    "Spanish": spanishBibleVersionsBooksNumberOfChapters
}