
export const bibleBooks: { [key: string]: { [key: number]: string } } = {
    "KJV": {
        1: "Genesis",
        2: "Exodus",
        3: "Leviticus",
        4: "Numbers",
        5: "Deuteronomy",
        6: "Joshua",
        7: "Judges",
        8: "Ruth",
        9: "1 Samuel",
        10: "2 Samuel",
        11: "1 Kings",
        12: "2 Kings",
        13: "1 Chronicles",
        14: "2 Chronicles",
        15: "Ezra",
        16: "Nehemiah",
        17: "Esther",
        18: "Job",
        19: "Psalms",
        20: "Proverbs",
        21: "Ecclesiastes",
        22: "Song of Solomon",
        23: "Isaiah",
        24: "Jeremiah",
        25: "Lamentations",
        26: "Ezekiel",
        27: "Daniel",
        28: "Hosea",
        29: "Joel",
        30: "Amos",
        31: "Obadiah",
        32: "Jonah",
        33: "Micah",
        34: "Nahum",
        35: "Habakkuk",
        36: "Zephaniah",
        37: "Haggai",
        38: "Zechariah",
        39: "Malachi",
        40: "Matthew",
        41: "Mark",
        42: "Luke",
        43: "John",
        44: "Acts",
        45: "Romans",
        46: "1 Corinthians",
        47: "2 Corinthians",
        48: "Galatians",
        49: "Ephesians",
        50: "Philippians",
        51: "Colossians",
        52: "1 Thessalonians",
        53: "2 Thessalonians",
        54: "1 Timothy",
        55: "2 Timothy",
        56: "Titus",
        57: "Philemon",
        58: "Hebrews",
        59: "James",
        60: "1 Peter",
        61: "2 Peter",
        62: "1 John",
        63: "2 John",
        64: "3 John",
        65: "Jude",
        66: "Revelation"
    },
    "RV1960": {
        1: "Génesis",
        2: "Éxodo",
        3: "Levítico",
        4: "Números",
        5: "Deuteronomio",
        6: "Josué",
        7: "Jueces",
        8: "Rut",
        9: "1 Samuel",
        10: "2 Samuel",
        11: "1 Reyes",
        12: "2 Reyes",
        13: "1 Crónicas",
        14: "2 Crónicas",
        15: "Esdras",
        16: "Nehemías",
        17: "Ester",
        18: "Job",
        19: "Salmos",
        20: "Proverbios",
        21: "Eclesiastés",
        22: "Cantares",
        23: "Isaías",
        24: "Jeremías",
        25: "Lamentaciones",
        26: "Ezequiel",
        27: "Daniel",
        28: "Oseas",
        29: "Joel",
        30: "Amós",
        31: "Abdías",
        32: "Jonás",
        33: "Miqueas",
        34: "Nahúm",
        35: "Habacuc",
        36: "Sofonías",
        37: "Hageo",
        38: "Zacarías",
        39: "Malaquías",
        40: "Mateo",
        41: "Marcos",
        42: "Lucas",
        43: "Juan",
        44: "Hechos",
        45: "Romanos",
        46: "1 Corintios",
        47: "2 Corintios",
        48: "Gálatas",
        49: "Efesios",
        50: "Filipenses",
        51: "Colosenses",
        52: "1 Tesalonicenses",
        53: "2 Tesalonicenses",
        54: "1 Timoteo",
        55: "2 Timoteo",
        56: "Tito",
        57: "Filemón",
        58: "Hebreos",
        59: "Santiago",
        60: "1 Pedro",
        61: "2 Pedro",
        62: "1 Juan",
        63: "2 Juan",
        64: "3 Juan",
        65: "Judas",
        66: "Apocalipsis"
    }
}
